# Generated by Django 5.2.1 on 2025-08-19 07:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='모델명')),
                ('version', models.CharField(max_length=20, verbose_name='버전')),
                ('status', models.CharField(choices=[('training', '훈련 중'), ('completed', '완료'), ('failed', '실패'), ('paused', '일시정지')], default='training', max_length=20, verbose_name='상태')),
                ('dataset_name', models.CharField(max_length=100, verbose_name='데이터셋')),
                ('gpu_info', models.CharField(max_length=100, verbose_name='GPU 정보')),
                ('memory_info', models.CharField(max_length=50, verbose_name='메모리 정보')),
                ('total_epochs', models.IntegerField(default=100, verbose_name='총 에포크')),
                ('current_epoch', models.IntegerField(default=0, verbose_name='현재 에포크')),
                ('batch_size', models.IntegerField(default=1, verbose_name='배치 크기')),
                ('learning_rate', models.FloatField(default=0.01, verbose_name='학습률')),
                ('image_size', models.IntegerField(default=640, verbose_name='이미지 크기')),
                ('optimizer', models.CharField(default='Adam', verbose_name='옵티마이저')),
                ('augmentation', models.BooleanField(default=True, verbose_name='데이터 증강')),
                ('early_stopping', models.BooleanField(default=True, verbose_name='조기 종료 사용')),
                ('patience', models.IntegerField(default=10, verbose_name='조기 종료 patience')),
                ('description', models.CharField(max_length=16000, verbose_name='설명')),
                ('dataset_path', models.CharField(max_length=6000, verbose_name='데이터셋 경로')),
                ('config', models.CharField(max_length=16000, verbose_name='설정정보 ')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField(verbose_name='에포크')),
                ('train_loss', models.FloatField(verbose_name='훈련 손실')),
                ('val_loss', models.FloatField(verbose_name='검증 손실')),
                ('map50', models.FloatField(verbose_name='mAP@0.5')),
                ('map95', models.FloatField(verbose_name='mAP@0.5:0.95')),
                ('precision', models.FloatField(default=0.0, verbose_name='정밀도')),
                ('recall', models.FloatField(default=0.0, verbose_name='재현율')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='training.trainingsession')),
            ],
            options={
                'ordering': ['epoch'],
                'unique_together': {('session', 'epoch')},
            },
        ),
        migrations.CreateModel(
            name='ClassMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='클래스명')),
                ('precision', models.FloatField(verbose_name='정밀도')),
                ('recall', models.FloatField(verbose_name='재현율')),
                ('f1_score', models.FloatField(verbose_name='F1 점수')),
                ('instances', models.IntegerField(verbose_name='인스턴스 수')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_metrics', to='training.trainingsession')),
            ],
            options={
                'unique_together': {('session', 'class_name')},
            },
        ),
    ]
