# Generated by Django 5.2.1 on 2025-08-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainingsession_updated_at'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE training_trainingsession 
            ADD COLUMN IF NOT EXISTS total_epochs integer DEFAULT 100;
            """,
            reverse_sql="""
            ALTER TABLE training_trainingsession 
            DROP COLUMN IF EXISTS total_epochs;
            """
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE training_trainingsession 
            ADD COLUMN IF NOT EXISTS current_epoch integer DEFAULT 0;
            """,
            reverse_sql="""
            ALTER TABLE training_trainingsession 
            DROP COLUMN IF EXISTS current_epoch;
            """
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE training_trainingsession 
            ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
            ALTER TABLE training_trainingsession 
            DROP COLUMN IF EXISTS updated_at;
            """
        ),
    ]
