# Generated by Django 5.2.1 on 2025-08-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20250818_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='total_epochs',
            new_name='epochs',
        ),
    ]
