# Generated by Django 5.2.1 on 2025-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20250818_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='epochs',
            field=models.IntegerField(default=100, verbose_name='총 에포크'),
        ),
    ]
