# Generated by Django 5.2.4 on 2025-08-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_trainingsession_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmetric',
            name='created_id',
            field=models.CharField(max_length=500, verbose_name='생성자ID'),
        ),
        migrations.AlterField(
            model_name='classmetric',
            name='updated_id',
            field=models.CharField(max_length=500, verbose_name='수정자ID'),
        ),
        migrations.AlterField(
            model_name='trainingmetric',
            name='created_id',
            field=models.CharField(max_length=500, verbose_name='생성자ID'),
        ),
        migrations.AlterField(
            model_name='trainingmetric',
            name='updated_id',
            field=models.CharField(max_length=500, verbose_name='수정자ID'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='created_id',
            field=models.CharField(max_length=500, verbose_name='생성자ID'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='updated_id',
            field=models.CharField(max_length=500, verbose_name='수정자ID'),
        ),
    ]
