# Generated by Django 4.2.7 on 2025-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_trainingsession_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='notify_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='notify_method',
            field=models.CharField(default='email', max_length=10),
        ),
    ]
