# Generated by Django 5.2.4 on 2025-08-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_classmetric_created_id_and_more'),
        ('training', '0006_trainingsession_notify_email_and_more'),
    ]

    operations = [
    ]
