# Generated by Django 5.2.4 on 2025-08-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_merge_20250822_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='notify_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='알림이메일'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='notify_method',
            field=models.CharField(default='email', max_length=10, verbose_name='알림구분'),
        ),
    ]
