"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# from decouple import config  # 2025.08.06 ngins7512 추가/대시보드 관련

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4b-f#wizd(_q(o-mfxpvnt*5o1t2#@lk7q(yf_wgm@=ru*p9an"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# 2025.08.06 ngins7512 추가/대시보드 관련
# DEBUG = config("DEBUG", default=True, cast=bool)

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]


# Application definition
# form_tags / ngins7512 / 2025.08.06
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "app",               # ← 이게 빠져 있으면 Django가 templatetags를 못 찾음! 로그인 관련
    "corsheaders",
    "training",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # "DIRS": [],
        "DIRS": [
            BASE_DIR / 'accounts' / 'templates',
            BASE_DIR / "app" / "templates",
            BASE_DIR / "training" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "postgres",  # DB 이름
        "USER": "postgres",  # 사용자 이름
        "PASSWORD": "yolo11ai",  # 비밀번호
        "HOST": "postgres.cxg2cwseemwh.ap-northeast-2.rds.amazonaws.com",  # 또는 실제 DB 서버 주소
        "PORT": "5432",  # PostgreSQL 기본 포트
    }
}

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/logout/"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = "ko-kr"  # 2025.08.06 ngins7512 추가/대시보드 관련

# TIME_ZONE = "UTC"
TIME_ZONE = "Asia/Seoul"  # 2025.08.06 ngins7512 추가/대시보드 관련
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
# STATIC_ROOT = BASE_DIR / "staticfiles" # 2025.08.10 ngins7512

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


# 대시보드 관련소스에서 추가
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True

# 1. Celery 설정 확인 (celery.py)

# 2. Django 설정에 Redis 브로커 추가
# Celery + Redis 를 위한 설정 (https://github.com/microsoftarchive/redis/releases 설치)
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0" # Celery는 기본적으로 결과를 저장하지 않지만, 설정하면 결과도 확인
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# 3. Redis 서버 실행 여부 확인
# redis-server
# (pytorch_env) C:\Users\ngins\Git\python.yolo>redis-server

# 4. Celery 워커 실행
# celery -A config worker --loglevel=info

# 5. 작업 함수(task) 정의 확인
# # app/tasks.py

# 6. 작업 호출 예시

# 추가 디버깅 팁
# pip show celery
# pip show billiard

# redis-cli ping 명령어로 Redis 연결 확인: PONG이 나오면 정상입니다.
# (pytorch_env) C:\Users\ngins\Git\python.yolo>redis-cli ping   
# PONG 