# Generated by Django 5.2.1 on 2025-08-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='updated_at',
        ),
    ]
