# Generated by Django 5.2.4 on 2025-08-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20250818_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
    ]
